name: 'Add Labels Deterministically'
description: 'Adds labels to an issue, but the color of the label will always be generated deterministically. If label does not exist this will try to create it.'
author: 'benlei'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play'
  color: 'blue'

# Define your inputs here.
inputs:
  repository:
    description: 'The repository to add the label to.'
    required: false
    default: ${{ github.repository }}
  token:
    description: 'The GitHub token to use for authentication.'
    required: true
    default: ${{ github.token }}
  issue-number:
    description: 'The issue number to add the label to.'
    required: true
  labels:
    description: 'The labels to add to the issue, separated by a comma.'
    required: true

runs:
  using: node20
  main: dist/index.js
